---
name: PR checks
on:
  pull_request:
    types: [opened, edited, synchronize, reopened, unlocked]
permissions:
  contents: read
jobs:
  check-conventional-commit:
    name: Check commit messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d  # v10.0.1
      - name: Check commit messages
        run: uvx --no-build --from commitizen==4.18.0 cz check --rev-range "FETCH_HEAD~.."
