---
name: PR checks
on:
  pull_request:
    types: [opened, edited, synchronize, reopened, unlocked]
permissions:
  contents: read
jobs:
  check-conventional-commit:
    name: Check commit messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: 3.x
      - run: pip install commitizen
      - name: Check commit messages
        run: cz check --rev-range "FETCH_HEAD~.."
